# This is a basic fully hermetic run of Lighthouse, that saves results as run artifacts.
name: LHCI-upload-artifact
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: treosh/lighthouse-ci-action@v2
      - name: Run Lighthouse on urls
        uses: ./
        with:
          urls: |
            https://treo.sh/
            https://treo.sh/demo
