# This is a basic fully hermetic run of Lighthouse, that saves results as run artifacts.
name: LHCI-upload-artifact
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run Lighthouse on urls
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://treo.sh/
            https://treo.sh/demo
